### ISSUE TITLE
Wrong characters in the object. [""]

### ISSUE THREAD

**Issue by capitaenz** [frankjoke/ioBroker.systeminfo#20]
Unfortunately the adapter generates the characters [""] and I cannot process the filtered number any further.
How can I remove the characters?
![Systeminfo1](https://user-images.githubusercontent.com/1240236/85256582-c569dc80-b464-11ea-88c1-61b1d2ed4bff.JPG)
![Systeminfo2](https://user-images.githubusercontent.com/1240236/85256588-c733a000-b464-11ea-952d-81d284663b62.JPG)

[https://forum.iobroker.net/topic/8672/neuer-adapter-systeminfo-auf-git-und-npm/63](url)

**Comment by frankjoke** [comment]
As mentioned in the forum already, the `""` are generated because this is a string and not a number. The reason is because javascript cannot parse European numbers with `,` as decimal point, you nee to use `.` for decimal point. To convert this string to a number you could write `Number(_string_.replace(",","."))`
